[project]
authors = [
    "Marek Novotny <marek.novotny@natur.cuni.cz>",
    "Martin Fleischmann <martin@martinfleischmann.net>"
    ]
channels = ["conda-forge"]
description = "Streetscape analysis based on Araldi and Fusco (2024?)"
name = "streetscape"
platforms =  ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.2.2,<3"
geopandas = ">=1.0.1,<2"
matplotlib = ">=3.9.2,<4"
rtree = ">=1.3.0,<2"
shapely = ">=2.0.6,<3"
numpy = ">=2.1.0,<3"
toml = ">=0.10.2,<0.11"
scikit-learn = ">=1.5.1,<2"
seaborn = ">=0.13.2,<0.14"
jupyter = ">=1.0.0,<2"
rasterio = ">=1.3.10,<2"
