[project]
authors = ["Martin Fleischmann <martin@martinfleischmann.net>"]
channels = ["conda-forge"]
description = "Development of streetscape module for momepy."
name = "streetscape"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
momepy = ">=0.9.1,<0.10"
rioxarray = ">=0.17.0,<0.18"
xvec = ">=0.3.0,<0.4"
ipykernel = ">=6.29.5,<7"
jupyterlab = ">=4.3.1,<5"
pyarrow = ">=18.1.0,<19"
matplotlib = ">=3.9.2,<4"
